site_name: Corecos Documentation
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Reference: reference.md
  - Configuration: config.md
  - Notice: notice.md
  - Phaser: phaser.md
  - Troubleshooting: troubleshooting.md
  - Contributing: contributing.md
  - License: license.md
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dungs072
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/nothing
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nothing/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
copyright: |
  &copy; 2025 <a href="https://github.com/dungs072"  target="_blank" rel="noopener">dungs72</a>